name: Lottery Data Scraper

on:
  schedule:
    # Runs at 10:00 UTC (which is 5:00 AM EST) on Wednesday and Saturday
    # This ensures we catch the Tuesday and Friday draws
    - cron: '0 10 * * 3,6'
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  scrape-and-recommend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python scrape.py

    - name: Run formatter
      run: |
        python formatter.py

    - name: Generate recommendations
      run: |
        # Create directory if it doesn't exist
        mkdir -p recommendation_history
        # Generate new heatmap and recommendations
        python recommender.py

    - name: Get latest heatmap file
      id: get_latest
      run: |
        LATEST_FILE=$(ls -t recommendation_history/*_heatmap.png | head -n1)
        FILENAME=$(basename "$LATEST_FILE")
        echo "FILENAME=$FILENAME" >> $GITHUB_OUTPUT

    - name: Send to Discord
      if: always()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          New Lotto Max heatmap generated!
          https://github.com/${{ github.repository }}/blob/main/recommendation_history/${{ steps.get_latest.outputs.FILENAME }}

    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet lottery_results_final.json lottery_results.csv recommendation_history || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changes exist
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lottery_results_final.json lottery_results.csv recommendation_history/
        git commit -m "Update lottery data and heatmap [automated]"
        git push
      env:
        GITHUB_TOKEN: ${{ github.token }}
